version: 2

builds:
  - main: ./main.go
    binary: microcks
    env:
      - CGO_ENABLED=0

release:
  prerelease: auto

universal_binaries:
  - replace: true
    name_template: microcks

signs:
  - artifacts: checksum
    cmd: gpg2
    args:
      - "--batch"
      - "-u"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

brews:
  - name: microcks
    homepage: https://github.com/microcks/microcks-cli
    repository:
      owner: microcks
      name: homebrew-tap

nfpms:
  - id: microcks
    package_name: microcks
    vendor: Microcks
    maintainer: Microcks <info@microcks.io>
    description: CLI for Microcks.
    homepage: https://github.com/microcks/microcks-cli
    license: Apache 2.0
    formats:
      - deb
      - rpm

sboms:
  - artifacts: archive

checksum:
  name_template: "checksums.txt"
