version: 2
project_name: microcks-cli

before: 
  hooks:
    - go mod tidy

builds:
  - main: ./main.go
    binary: microcks-cli
    env:
      - CGO_ENABLED=0
    goos: 
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64

archives:
- format: tar.gz
  format_overrides:
    - goos: windows
      format: zip

release:
  name_template: "Microcks CLI v{{.Tag}}"
  draft: true
  disable: false
  prerelease: auto
  github:
    owner: microcks
    name: microcks-cli

universal_binaries:
  - replace: true

signs:
  - artifacts: checksum
    cmd: gpg2
    args:
      - "--batch"
      - "-u"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

brews:
  - name: microcks-cli
    homepage: https://github.com/microcks/microcks-cli
    repository:
      owner: microcks
      name: homebrew-tap

sboms:
  - artifacts: archive

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters: 
    exclude:
      - '^docs:'
      - '^test:'
      - typo
